### ISSUE TITLE
Installation Error python 3.5

### ISSUE THREAD

**Issue by Jawwadjlf** [j2labs/pyango_view#1]
site-packages\pyango_view__init__.py", line 37
    except OSError, e:
                  ^
SyntaxError: invalid syntax

**Comment by j2labs** [comment]
I haven't used this project in years. Definitely not built for Python 3.x.

Feel free to submit a PR.

**Comment by Jawwadjlf** [comment]
Hi,

I need help , I have written complete code, and it is working fine. But i
am getting little bit wrong output.
I think you will have completed this.   I have this question on
stackoverflow .  Moreover output has beed attached.

http://stackoverflow.com/questions/39000761/pil-draw-text-is-displaying-string-containing-arabic-ligature-as-two-separate


## 

Regards:
Jawwad Rafiq

**Comment by j2labs** [comment]
This project does nothing more than put together some command line arguments and then calls pango-view as a subprocess: https://github.com/j2labs/pyango_view/blob/master/pyango_view/__init__.py#L35

Please reach out to the pango team for help.
